### ISSUE TITLE
Which tool do you use to draw the architecture.gif?

### ISSUE THREAD

**Issue by dekura** [alexandre01/deepsvg#8]
Hi, @alexandre01 , thank you for your genius work, beyond the impressive deep learning technologies, I'm also interested your diagrammatic drawing. Which tool do you use to draw the [architecture.gif](https://blog.alexandrecarlier.com/deepsvg/imgs/architecture.gif)?  Or the diagrams in your paper, all of them looks fancy to me and I hope to draw pictures of same style in my work.

Thank you~

**Comment by alexandre01** [comment]
Hi,
Thanks!

For the diagram drawing, I used Figma. With our paper DeepSVG, we try to follow the idea to be as open-source as possible and therefore even make available the design file of our architecture! Here is the link:

https://www.figma.com/file/d3tIdurkuN75JAz4YJWCoO/DeepSVG?node-id=0%3A1

Feel free to reuse/modify it or just be inspired by (with proper citation of course!)

```
@misc{carlier2020deepsvg,
    title={DeepSVG: A Hierarchical Generative Network for Vector Graphics Animation},
    author={Alexandre Carlier and Martin Danelljan and Alexandre Alahi and Radu Timofte},
    year={2020},
    eprint={2007.11301},
    archivePrefix={arXiv},
    primaryClass={cs.CV}
}
```

For the animation (related to issue #2 ), it is unfortunately a little less accessible since I used AfterEffects which takes a bit of practice and has a quite steep learning curve...

**Comment by dekura** [comment]
> Hi,
> Thanks!
> 
> For the diagram drawing, I used Figma. With our paper DeepSVG, we try to follow the idea to be as open-source as possible and therefore even make available the design file of our architecture! Here is the link:
> 
> https://www.figma.com/file/d3tIdurkuN75JAz4YJWCoO/DeepSVG?node-id=0%3A1
> 
> Feel free to reuse/modify it or just be inspired by (with proper citation of course!)
> 
> ```
> @misc{carlier2020deepsvg,
>     title={DeepSVG: A Hierarchical Generative Network for Vector Graphics Animation},
>     author={Alexandre Carlier and Martin Danelljan and Alexandre Alahi and Radu Timofte},
>     year={2020},
>     eprint={2007.11301},
>     archivePrefix={arXiv},
>     primaryClass={cs.CV}
> }
> ```
> 
> For the animation (related to issue #2 ), it is unfortunately a little less accessible since I used AfterEffects which takes a bit of practice and has a quite steep learning curve...

Thanks a lot!
